### ISSUE TITLE
[Repeat Issue] Import Issue, getting DLL error.

### ISSUE THREAD

**Issue by pnp-peeyush** [sonofeft/RocketCEA#12]
pip install of rocketcea was successful, I think the MinGW installation was also done, couldn't find a way to verify the installation. I think successful rocketcea installation is good enough proof that MinGW installation was successful. But when i try:
`from rocketcea.cea_obj import CEA_Obj` 
i get the following error message:

Traceback (most recent call last):
  File "C:\Users\Peeyush Ramteke\AppData\Local\Programs\Python\Python38\lib\site-packages\rocketcea\cea_obj.py", line 52, in <module>
    import rocketcea.py_cea as py_cea
ImportError: DLL load failed while importing py_cea: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Peeyush Ramteke\AppData\Local\Programs\Python\Python38\lib\site-packages\rocketcea\cea_obj.py", line 60, in <module>
    import rocketcea.py_cea as py_cea
ImportError: DLL load failed while importing py_cea: The specified module could not be found.

Couldn't find a proper solution for this. Plz halp!

**Comment by sonofeft** [comment]
On Windows, that error message normally means that for FORTRAN compile was not done as part of the pip install, such that the DLL is not available.
If you are using python 3.8 on Windows, you should know that I do not yet support python 3.8 due to some MinGW issues.
