### ISSUE TITLE
Function get_eps_at_PcOvPe fails in a frozen condition

### ISSUE THREAD

**Issue by d-shado** [sonofeft/RocketCEA#15]
I'm getting errors in frozen ivac because the input is only epsilon and get_eps_at_PcOvPe function works only in equilibrium conditions. 
I can't also get gamma at the exit because the main input is always epsilon so I'm not able to use it to evaluate by hand the expansion ratio using the isentropic relations.

**Comment by sonofeft** [comment]
If I understand correctly, you'd like a frozen flag added to get_eps_at_PcOvPe like:
epsFrozen = C.get_eps_at_PcOvPe( Pc=100.0, MR=1.0, PcOvPe=1000.0, frozen=True)

perhaps also for get_exit_MolWt_gamma

Is that correct?

**Comment by d-shado** [comment]
Yes! Maybe with also the flag for the frozen in throat or chamber. I would do it myself, but I don't know how to extract a direct CEA output as the frozen area ratio is.
Thank's for your help.

**Comment by d-shado** [comment]
I solved my problem adding these flags in the functions and in the "setupcard". I didn't know that was so easy, maybe because I don't know python very well. 
Thank's anyway for your help, you created something very, very, useful.

**Comment by sonofeft** [comment]
You can check your changes with a full ouput something like the script below.
For the future, I think adding a frozen flag to a number of methods is a good idea.

from rocketcea.cea_obj import CEA_Obj

ispObj = CEA_Obj( oxName='LOX', fuelName='LH2')
s = ispObj.get_full_cea_output( frozen=1, frozenAtThroat=0,
                                Pc=[1000, 2000], # number or list of chamber pressures
                                MR=[6.0, 7.0],   # number or list of mixture ratios
                                PcOvPe=[100,200],# number or list of Pc/Pexit
                                eps=[40.0,60],   # number or list of supersonic area ratios
                                subar=[3,2],     # number or list of subsonic area ratios
                                short_output=0,  # 0 or 1 to control output length
                                pc_units='psia', # pc_units = 'psia', 'bar', 'atm', 'mmh'
                                output='siunits')# output = 'calories' or 'siunits'
print( s )
