### ISSUE TITLE
Fortran runtime error when using "get_transport" even with throat, chamber or exit.

### ISSUE THREAD

**Issue by d-shado** [sonofeft/RocketCEA#16]
I tried using the example in "Standard examples", both with my setup and with Google Colaboratory. 
Other than that Rocketcea is working flawlessly.
This is the code:

```
from rocketcea.cea_obj import CEA_Obj

ispObj = CEA_Obj( oxName='LOX', fuelName='LH2')
Cp, visc, cond, Pr = ispObj.get_Chamber_Transport(Pc=1000.0, MR=6.0)
Cp, visc, cond, Pr = ispObj.get_Chamber_Transport(Pc=1000.0, MR=6.0, frozen=1)

Cp, visc, cond, Pr = ispObj.get_Throat_Transport(Pc=1000.0, MR=6.0)
Cp, visc, cond, Pr = ispObj.get_Throat_Transport(Pc=1000.0, MR=6.0, frozen=1)

Cp, visc, cond, Pr = ispObj.get_Exit_Transport(Pc=1000.0, MR=6.0, eps=40.0)
Cp, visc, cond, Pr = ispObj.get_Exit_Transport(Pc=1000.0, MR=6.0, eps=40.0, frozen=1)
```

The error that I get is:

`At line 5462 of file rocketcea/py_cea.f (unit = 13, file = '/usr/local/lib/python3.6/dist-packages/rocketcea/temp.scr')
Fortran runtime error: End of file`

**Comment by sonofeft** [comment]
Thanks... I suspect a permissions issue with writing and then reading '/usr/local/lib/python3.6/dist-packages/rocketcea/temp.scr'

I will dust off my FORTRAN maintainer's hat and look into it.

**Comment by sonofeft** [comment]
I have uploaded version 1.1.24 to PyPI that should solve the problem.
(I duplicated your problem and version 1.1.24 seemed to fix it.)

Let me know if you have any problems.
