### ISSUE TITLE
Can't create monopropellant N2

### ISSUE THREAD

**Issue by pekpuglia** [sonofeft/RocketCEA#23]
With CEA's GUI application, I can easily select to use N2 as a monopropellant. However, RocketCEA does not allow me to create a CEA_Obj instance with `propName="N2`. Here is the code I used:
`
from rocketcea.cea_obj import CEA_Obj
`
`
CEA_Obj(propName="N2")
`
which yields the following error:
> ERROR... bad propellant name (N2) in cea_obj.py
<rocketcea.cea_obj.CEA_Obj object at 0x7efc86f71fa0>

Is this the expected behavior? Is there any other way of choosing arbitrary substances from thermo.lib?

**Comment by sonofeft** [comment]
N2 is not a library monopropellant.
You can reproduce the On-line CEA GUI results with the following:

```
from rocketcea.cea_obj import CEA_Obj
from rocketcea.cea_obj import add_new_propellant

prop_name = 'N2_at_1000K'
card_str = "name N2                wt%=100.0000  t,k=1000.0"

add_new_propellant(prop_name, card_str)

ispObj = CEA_Obj(propName=prop_name)
s = ispObj.get_full_cea_output( Pc=100.0,  eps=10.0, short_output=1)

print(s)

```
