### ISSUE TITLE
Help: Recompile py_cea after installation

### ISSUE THREAD

**Issue by cedricgould** [sonofeft/RocketCEA#24]
@solofeft,
Really like the work you've done here!  Just trying to understand and possibly extend its functionality.
If I have this right, RocketCEA will write CEA input files making requests for multiple sub- and supersonic area ratio nozzles in the same CEA run, but querying output results beyond the py_cea.inc INCLUDE variable NCOL value get clipped.  For example, if I request more than 6 supersonic nozzle area ratios and the CEA results spill to a second printed grouping, py_cea doesn't know about and isn't able to access those results.  By default, it appears the py_cea.inc file uses the CEA default NCOL value of 8, so only the first 8 outputs for a given combustion chamber pressure and mixture ratio are available to the CEA_Obj.  If I can edit py_cea.inc NCOL=30, then I'd be able to max out CEA's ability to provide both sub- and supersonic nozzle outputs per run (rather than the hassle of tracking additional printed rows from the normal CEA output file).  The trouble I'm having is recompiling py_cea after rocketcea's baseline installation.  Do you have a process recommended for recompiling py_cea after an otherwise successful rocketcea installation so that other modifications/updates like this one can be made?  Thanks for your help!
Regards

**Comment by sonofeft** [comment]
The following Windows BAT file can be used to recompile  your installation of RocketCEA.
You will need to change the hard-coded paths in the following batch file instructions
for the location of MinGW and your python interpreter.


```
rem set python path variable (Default is Python 3.7 64 bit)
IF "%1"=="" ( SET "MYPYTHONPATH=D:\Python37_64" ) ELSE ( SET "MYPYTHONPATH=D:\Python%1_64" )

rem Make sure that PATH is as simple as possible
set PATH=C:\MinGW\mingw64\bin;C:\MinGW\mingw64\lib;%MYPYTHONPATH%;%MYPYTHONPATH%\Scripts

pip uninstall -y rocketcea

python setup.py build --compiler=mingw32

python setup.py install

rem optionally create distribution files
python setup.py sdist bdist_wheel

rem Test the compiled module
python -c "from rocketcea.cea_obj import CEA_Obj; C=CEA_Obj(oxName='LOX', fuelName='LH2'); print(C.get_Isp())"

```
