### ISSUE TITLE
"Runtime Error: End of file" Occurring While Calling 'get_Chamber_Transport(...)'

### ISSUE THREAD

**Issue by Frank-ZW** [sonofeft/RocketCEA#25]
Hey all,

I appreciate the amount of work you guys spent making this wrapper! As an AE student, this project is a godsend.

I'm still in the process of fully learning RocketCEA, but I'm having trouble with a couple of functions that seem to always produce a runtime error. Anytime I call `get_Chamber_Transport(...)`, `get_Exit_Transport(...)`, and `get_Throat_Transport(...)`, the program produces the following error:

```
At line 5462 of file rocketcea/py_cea.f (unit = 13, file = 'C:\Users\XXX\RocketCEA\temp.dat')
Fortran runtime error: End of file

Process finished with exit code 2
```

I have no idea what could be causing this because everything else about the module works, just those specific methods seem to result in a runtime error. I see that another [issue](https://github.com/sonofeft/RocketCEA/issues/8) regarding those methods was posted a couple of years ago, but the solution seemed to be "update RocketCEA" and I believe I have the latest version. I'm using Python 3.9 with Anaconda. Is it something wrong with the way I installed Fortran?

Any help is appreciated! Thank you for your time!

To reproduce the issue I'm having, create a new project and paste the following code:
```
from rocketcea.cea_obj import CEA_Obj

if __name__ == '__main__':
    cea_obj = CEA_Obj(oxName='LOX', fuelName='Kerosene')
    properties = cea_obj.get_Chamber_Transport(Pc=250, MR=1.8, eps=3)
```

And got the Fortran runtime error. Let me know if it works for you.

**Comment by sonofeft** [comment]
This is confusing... 
If you go to the repository at: https://github.com/sonofeft/RocketCEA/blob/master/rocketcea/py_cea.f
you will see that there is no such line in py_cea.f

I will leave the issue open, but let me know if a fresh install solves the problem.

**Comment by Frank-ZW** [comment]
I ran `pip uninstall rocketcea` in my conda environment and reinstalled with `pip install rocketcea` and still have the same error. Do you know what the error means by "...\RocketCEA\temp.dat"? Would downloading `rocketcea/py_cea.f` and replacing the one I have on my computer fix anything?

**Comment by sonofeft** [comment]
The FORTRRAN runs on a lot of other machines w/o error so...
the error seems to be unique to your setup.
It would be very interesting to know if your download and replace idea would work, however, you could no longer use pip to install it. You would need to manually run setup.py.

Look at issue #24 for help with that: https://github.com/sonofeft/RocketCEA/issues/24

You might also look at the conda comments at: https://rocketcea.readthedocs.io/en/latest/quickstart.html#anaconda-windows-batch-file

Please let me know if any of this helps.

**Comment by Frank-ZW** [comment]
Quick question regarding Issue #24: for the batch file, I have Anaconda installed instead of Python. Would I replace the Python path with the `python.exe` file in Anaconda?

**Comment by sonofeft** [comment]
Try the Anaconda batch file instructions at: 
https://rocketcea.readthedocs.io/en/latest/quickstart.html#anaconda-windows-batch-file

To find your python.exe path do the following in a command prompt:
```
import sys
sys.executable

```

Let me know if that works.

**Comment by Frank-ZW** [comment]
I don't think that changed anything (same error popped up) and I also completely removed and re-created the environment that I installed RocketCEA to. One thing I did notice, however, was that using `LH2` and `LOX` as the fuel and oxidizer worked just fine. As in running
```
from rocketcea.cea_obj import CEA_Obj

if __name__ == '__main__':
	cea_obj = CEA_Obj(fuelName='LH2', oxName='LOX')
	print(cea_obj.get_Chamber_Transport(Pc=250, MR=1.8, eps=3))
	print(cea_obj.get_Throat_Transport(Pc=250, MR=1.8, eps=3))
	print(cea_obj.get_Exit_Transport(Pc=250, MR=1.8, eps=3))
```
Produced the output
```
(1.5488556763074002, 0.47320165501905215, 1.210882782726843, 0.6052782976761931)
(1.4955331913652374, 0.4268640048930907, 1.065034735305588, 0.5994070112028211)
(1.3414337167903312, 0.27194707628430503, 0.6553191747071077, 0.5566737421858051)

Process finished with exit code 0
```
I tried a few other propellants and it only seems to work for hydrogen and LOX.

**Comment by sonofeft** [comment]
In the past, odd-ball problems can be related to permissions or perhaps spaces in path names or extra long path names.

To test permissions, you might try running in a command prompt that is "run as administrator".

I don't use Anaconda, so I won't be much help there, but I do think Anaconda buries directories pretty deep in the user area, so extra long path names might exist.

Some less convenient options would be to install RocketCEA on Windows WSL (Windows Subsystem for Linux) or on Google Colaboratory. (both options are described on the Quickstart page of the docs)

**Comment by Frank-ZW** [comment]
I tried running CMD as administrator and it didn't change anything. However, after a bit of messing around with RocketCEA on CMD, I found that running
```
python -c "from rocketcea.cea_obj import CEA_Obj; C=CEA_Obj(oxName='XXX', fuelName='YYY'); print(C.get_full_cea_output(..., show_transport=1))"
```
Allowed me to run the transport functions without erroring. That is, before, the error was showing up for an Isopropanol-N2O fuel blend but running the following code in command prompt
```
python -c "from rocketcea.cea_obj import CEA_Obj; C=CEA_Obj(oxName='N2O', fuelName='Isopropanol'); print(C.get_full_cea_output(Pc=250.0, MR=3.50, eps=3.03, show_transport=1))"
```
And _then_ running
```
python -c "from rocketcea.cea_obj import CEA_Obj; C=CEA_Obj(oxName='N2O', fuelName='Isopropanol'); print(C.get_Chamber_Transport(Pc=250.0, MR=3.50, eps=3.03))"
```
Prints out
```
(0.5581840005382234, 0.8719909920135673, 1.0768349948622604, 0.4520018597813916)
```
Similar results were printed for the exit and throat transport properties. I have no idea why this works but it seems like the solution in the mean time would be to just run the `get_full_cea_output(...)` method with the `show_transport=1` parameter and the transport functions should work (if you're having that problem).

**Comment by sonofeft** [comment]
On my Windows installation of RocketCEA (not Anaconda) when I run your desired command:

`python -c "from rocketcea.cea_obj import CEA_Obj; C=CEA_Obj(oxName='N2O', fuelName='Isopropanol'); print(C.get_Chamber_Transport(Pc=250.0, MR=3.50, eps=3.03))"
`
I get: `(0.5581840005382234, 0.8719909920135673, 1.0768349948622604, 0.4520018597813916)`

straight away without any need to make your first "get_full_cea_output" call.

I'm going to close the issue because I think it is specific to your installation, but I will poke around the code a bit to see if I can find a possible connection between the "get_full_cea_output" and the proper execution of the direct command.
