### ISSUE TITLE
May I ask if this library supports tp and hp calculations? There is no relevant API in the document.

### ISSUE THREAD

**Issue by wangxiaochen19960107** [sonofeft/RocketCEA#27]
May I ask if this library supports tp and hp calculations? There is no relevant API in the document.

**Comment by sonofeft** [comment]
Look at the new propellant documentation at: https://rocketcea.readthedocs.io/en/latest/new_propellants.html
It describes how to change those input values of propellants.

There is also a detailed discussion at: https://rocketcea.readthedocs.io/en/latest/temperature_adjust.html

If you decide to create a for loop to generate a table of values, I recommend using a unique name for each ox, fuel or propellant.

For example if you set a varible "hp" in a loop, use it to set the name as shown below.
`add_new_oxidizer( 'my_prop_hp_%s'%hp,  card_str )`
