### ISSUE TITLE
constant temperature and pressure problems.

### ISSUE THREAD

**Issue by wangxiaochen19960107** [sonofeft/RocketCEA#28]
Dear author, rocketcea can use cea to calculate rocket problems. For problems such as constant temperature and pressure, adiabatic constant volume, is there any related api?

**Comment by sonofeft** [comment]
RockeCEA only runs rocket problems. 
For running in other modes (e.g. tp, hp, sh, etc.) I refer you to the CEA manuals.

https://ntrs.nasa.gov/api/citations/19950013764/downloads/19950013764.pdf
https://ntrs.nasa.gov/api/citations/19960044559/downloads/19960044559.pdf

I am unaware of other API interfaces to CEA that cover those modes.
