### ISSUE TITLE
temperature setting

### ISSUE THREAD

**Issue by wangxiaochen19960107** [sonofeft/RocketCEA#29]
Hello, I would like to know what is the temperature set during rocketcea making calculation, can it be changed? Thank you!

**Comment by sonofeft** [comment]
For nominal NASA CEA runs it is customary to run cryogenic liquid propellants at their normal boiling point and storable liquid propellants at room temperature. Gas and solid propellants are usually assumed to be at room temperature as well. Those are the assumptions that RocketCEA makes for nominal runs.

To run a propellant at a different starting temperature there is a detailed discussion for "Temperature Adjusts" at: https://rocketcea.readthedocs.io/en/latest/temperature_adjust.html
There is a helper function called "makeCardForNewTemperature" shown there that requires an input average heat capacity to scale from the nominal temperature to the new temperature.

There are similar helper functions, "newFuelWithNewState" and "newOxWithNewState" shown on 
https://rocketcea.readthedocs.io/en/latest/functions.html
That give more control over adjusting starting enthalpy and temperature.

You can also take more of a "hands on" approach by reviewing "New Propellants" at: https://rocketcea.readthedocs.io/en/latest/new_propellants.html#

For further help on NASA CEA input cards, look at the users manuals for NASA CEA.
https://ntrs.nasa.gov/api/citations/19950013764/downloads/19950013764.pdf
https://ntrs.nasa.gov/api/citations/19960044559/downloads/19960044559.pdf

**Comment by wangxiaochen19960107** [comment]
Thanks for your reply!
