### ISSUE TITLE
Differenr output from cea2 and rocketcea.

### ISSUE THREAD

**Issue by wangxiaochen19960107** [sonofeft/RocketCEA#30]
Dear author,
        I used the cea2 program included in rocketcea with same input, but got different output, I don't know where the problem is, so I want to ask you. I don’t know if there are any parameters to be set in some places
        ### Input:
                **propellants:**
                        name AP       N 1 H 4 CL 1 O 4 wt%=50.0 h,cal=-70666.62000000001 t(k)=298.15 rho.g/cc=1.95
                        name HMX   C 4 H 8 O 8 N 8 wt%=50.0 h,cal=17881.665 t(k)=298.15 rho.g/cc=1.9
                        name BTTN   C 4 H 7 O 9 N 3 wt%=50.0 h,cal=-97232.3 t(k)=298.15 rho.g/cc=1.52
                **parameters:**
                       Pc = 6.86MPa    PcOvPe = 67.703

        ### CEA2 output:
<img width="488" alt="a5c34953ad878eebcb25abf90818a33" src="https://user-images.githubusercontent.com/19171195/234465282-073a81fd-7b6a-4d7d-93d0-5bcad6e4faac.png">

        ### ROCKETCEA output:
<img width="485" alt="4da3c0b0a1c1642145f26dfe599fd7e" src="https://user-images.githubusercontent.com/19171195/234465378-bfc83d4d-676c-42b9-8c48-3635da78ad51.png">

**Comment by sonofeft** [comment]
You did not include your input files in your question, however, 
looking at your output, I strongly suspect that the input files are different for your CEA and RocketCEA runs.

I recommend that you run your RocketCEA case as shown in the example at: 
https://rocketcea.readthedocs.io/en/latest/std_examples.html#lox-lh2-performance
    
The CEA output from your run will show the CEA input near the top (right after the NASA banner).

Copy that section from the "reac" line to the "end" line and paste it into a CEA input file (for example "my_run.inp")
    
Run CEA with that file ("my_run.inp") as input and you should get the same output as RocketCEA.
