### ISSUE TITLE
Add products

### ISSUE THREAD

**Issue by wangxiaochen19960107** [sonofeft/RocketCEA#32]
Hello, I want to ask you. If I want to add the product, which file should I add? Thank you!

**Comment by sonofeft** [comment]
I'm not sure I understand the question, but if you are talking about RocketCEA, it is a multifile project with both python and FORTRAN code and it has dependencies on other python libraries. You might look at the RocketCEA quickstart page for an overview. https://rocketcea.readthedocs.io/en/latest/quickstart.html
