### ISSUE TITLE
Which version of python and numpy do I need to install

### ISSUE THREAD

**Issue by BoomBangPow** [sonofeft/RocketCEA#44]
When I run pip install rocket cea I get the errors/ warnings below. Which numpy version do i need?

`
SetuptoolsDeprecationWarning: setup.py install is deprecated.`

and 

```
      INFO: No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
      INFO: customize MSVCCompiler
      INFO: customize MSVCCompiler using build_ext
      INFO: CCompilerOpt.cc_test_flags[1073] : testing flags (/O2)
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      INFO: CCompilerOpt.cache_flush[857] : write cache to path -> C:\Users\sabri\AppData\Local\Temp\pip-install-bxun9xhh\rocketcea_1375851929e9414b90620f95d93a0d5c\build\temp.win-amd64-cpython-311\Release\ccompiler_opt_cache_ext.py
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for rocketcea
  Running setup.py clean for rocketcea
Failed to build rocketcea
ERROR: Could not build wheels for rocketcea, which is required to install pyproject.toml-based projects
```

**Comment by sonofeft** [comment]
I apologize for being asleep-at-the-wheel when numpy.distutils was deprecated.

I am currently trying to figure out the best solution for various platforms and python versions, however, the answer to your question is numpy version 1.22.4 is the last version to NOT give a deprecation warning. With that in mind, perhaps `pip install numpy==1.22.4` is the best solution. (Keep in mind, there is still a lot of testing to be done)

For python 3.9 thru 3.11, numpy versions 1.23.0 thru 1.26.4 should work, but will warn about deprecation.
Python 3.7 only supports up to numpy==1.21.6 which should work
Python 3.8 only supports up to numpy==1.24.4 which should work, but with deprecation warnings.
Python version 3.12 will throw an error installing any numpy below version 1.26.0

The long term solution is probably to convert over to building with meson, but I’m not there yet.

While I try to sort through all the issues, it might be easiest on Windows to use WSL (see https://rocketcea.readthedocs.io/en/latest/quickstart.html#windows-10-with-wsl )

I am hoping to put out more helpful install instructions soon.
