### ISSUE TITLE
python setup.py build --compiler=mingw32   run error

### ISSUE THREAD

**Issue by Bob0126pan** [sonofeft/RocketCEA#45]
when I run command "python setup.py build --compiler=mingw32 "  in win32-py39,
error raise 

INFO: Building import library (ARCH-x86): "D:\\VS_code\ RocketCEA\. venv\ libs\ libpython39.a"
error: [ Errno 2] No such file or directory: 'D:\\VS code1\ RocketCEA\\.venv\\ libs\\ python39. def'

**Comment by sonofeft** [comment]
You can find install help at: 
https://rocketcea.readthedocs.io/en/latest/quickstart.html#link-install-rocketcea

However, it looks like you are using a virtual environment on Windows.

Inside your activated virtual environment, the following should work:
```
pip install numpy matplotlib scipy

pip install rocketcea


```
