### ISSUE TITLE
add way to define optional points 

### ISSUE THREAD

**Issue by alexey-kruchenok** [sonofeft/RocketCEA#7]
in standard CEA there is a way to define subsonic/supersonic points and get multiple EXIT columns, like this:

problem case=test2
     rocket  equilibrium  frozen  nfz=1  tcest,k=3000
   p,psia=1000,
   sub,ae/at=50,
   sup,ae/at=50,
 react
.....

and get THEORETICAL ROCKET PERFORMANCE section with extra points

CHAMBER THROAT EXIT EXIT
 68.947   38.886   68.944  0.09614
 3375.23  3066.93  3375.21  1014.20
6.2875 0 3.9026 0 6.2873 0 2.9178-2
-1444.57 -2043.50 -1444.62 -5730.47
-2541.15 -3039.92 -2541.19 -6059.97

is there a way to do so with rocketCEA?

**Comment by sonofeft** [comment]
can you tell me which properties you would require to have subsonic options?

**Comment by sonofeft** [comment]
Added requested feature: https://rocketcea.readthedocs.io/en/latest/traditional_example.html
requires >= version 1.1.2
