### ISSUE TITLE
get_Enthalpies and get_Chamber_H yield different values

### ISSUE THREAD

**Issue by markuspinter** [sonofeft/RocketCEA#9]
I am trying to read the enthalpies as well as densities and other values from rocketcea using LOX and LH2 using this code:

	#from rocketcea.cea_obj_w_units import CEA_Obj
	from rocketcea.cea_obj import CEA_Obj

	def main():

	P1 = 300

	# ceaObj = CEA_Obj(oxName='LOX', fuelName='LH2', useFastLookup=0, makeOutput=0,
	# 		isp_units='m/sec', cstar_units='m/sec', pressure_units='Bar', temperature_units='K',
	# 		sonic_velocity_units='m/sec', enthalpy_units='J/kg', density_units='kg/m^3', specific_heat_units='J/kg-K')
	ceaObj = CEA_Obj(oxName='LOX', fuelName='LH2')

	#enthalpy in chamber
	chamberEnthalpy = ceaObj.get_Chamber_H(P1, 1, eps=40.0)
	#get enthalpies of engine
	enthalpies = ceaObj.get_Enthalpies(P1, 1, eps=40.0)
	#get densities of engine
	densities = ceaObj.get_Densities(P1, 1, eps=40.0)
	#chamber density
	chamberDensity = ceaObj.get_Chamber_Density(P1, 1, eps=40.0)
	#sonic velocity in chamber	
	chamberSonicVel = ceaObj.get_Chamber_SonicVel(P1, 1, eps=40.0)
	#chamber heat cap. viscosity, conductivity and prantl number
	chamberTransport = ceaObj.get_Chamber_Transport(P1, 1, eps=40.0, frozen=0)

	print("Densities in Engine " + str(densities))
	print("Density in Chamber " + str(chamberDensity))
	print("Enthalpy in Engine " + str(enthalpies))
	print("Enthalpy in Chamber " + str( chamberEnthalpy ))

	main()

when executing it the results are:

	Densities in Engine [   97456.56086048   154481.69929706 14320654.40302216]
	Density in Chamber 0.06405721631134928
	Enthalpy in Engine [ -293.23872262  -433.53167713 -1046.7461387 ]
	Enthalpy in Chamber -1048.9114065272818

I'm using version 1.1.12

I've looked up the code of get_Enthalpies and get_Chamber_H and they use the same functions in the end.

The weird thing is, when removing get_Chamber_SonicVel and get_Chamber_Transport they the density values are the same, but enthalpy not. When additionally removing the two densities functions, enthalpy is the same for both functions. 

I've even tried to create a new CEA_Obj after each of these functions, but that doesn't fix it.

When using cea_obj_w_units none of these above described "fixes" work. 

I also ran the basic_cea.py code you provided in the docs, but the results are fine.

Do you have any idea what the issue could be?

Thanks!

**Comment by sonofeft** [comment]
Fixed as of version 1.1.15
